### ISSUE TITLE
As a volunteer after the due date of my help request I'll get a private message with a link for a feedback request

### ISSUE THREAD

**Issue by barakd** [dorldor/help-on-the-way#15]
After the due date the help request, the user will receive a message through a communication channel (IM software, for stater we can assume WhatsApp) allowing him to send feedback & comment about the help request & the status of the elder.
![image](https://user-images.githubusercontent.com/7824284/34844005-bc2698cc-f718-11e7-8384-8ad74ee1d38a.png)

**Comment by GuyFliess** [comment]
Are we thinking SMS here?
it will be easiest to implement with any of the many Restfull services out there, but will have minor costs

**Comment by barakd** [comment]
We are thinking towards a private message to his WhatsApp or other IM software he is using, we should investigate & understand the technical possibility of doing this.
