### ISSUE TITLE
Adjust need to know to input to correct design

### ISSUE THREAD

**Issue by barakd** [dorldor/help-on-the-way#176]
We need to update the current design of the need to know component:
![image](https://user-images.githubusercontent.com/7824284/38516707-89a1e358-3c40-11e8-88c1-4ae006bb8ccb.png)

See:
https://github.com/dorldor/help-on-the-way/blob/master/specialist-dashboard/src/components/features/ticket/TicketNeedToKnowPoints.vue

To the correct design:

![image](https://user-images.githubusercontent.com/7824284/38516840-cebc75ac-3c40-11e8-96cc-36f988ca37c8.png)

**Comment by omerlive** [comment]
Pull request sent!

**Comment by barakd** [comment]
https://github.com/dorldor/help-on-the-way/issues/176 Done in.
