### ISSUE TITLE
As a specialist I can preview the help request summary, and assign to which groups I would like to send the help request to

### ISSUE THREAD

**Issue by barakd** [dorldor/help-on-the-way#22]
After inputting the ticket details #20 
As a specialist, I will be shown the ticket summary and will be able to choose which groups I want to assign the ticket to.

Early Stage Mock (just to get the intent)
![image](https://user-images.githubusercontent.com/7824284/34870613-55dbe3ee-f793-11e7-81e4-503ea9cff3c3.png)

**Comment by OhadRon** [comment]
Product thought - perhaps allow free editing of the text? and not just constrain to prefix/postfix. 

Group selection should also include group channel type (Whatsapp / Telegram / Email etc). Later on perhaps visualize the relevant area for each group.

**Comment by barakd** [comment]
Done
