### ISSUE TITLE
LTR and RTL support to volunteer app components

### ISSUE THREAD

**Issue by barakd** [dorldor/help-on-the-way#257]

**Comment by barakd** [comment]
See
https://vuetifyjs.com/en/framework/internationalization#rtl

**Comment by barakd** [comment]
This is going to require to update to vuetifiy 1.2.7 which is going to create a mess, but we have to deal with it

**Comment by doronkilzi** [comment]
upgrade to 1.27 pr: https://github.com/dorldor/help-on-the-way/pull/260
