### ISSUE TITLE
implement an entity search component 

### ISSUE THREAD

**Issue by barakd** [dorldor/help-on-the-way#56]
We need a component that allows searching an entity in the system & pick it,
then we will reuse that component for each entity picker in the system,
![image.png](https://images.zenhubusercontent.com/5a515ed2a016c5b034bc46c7/a942f5ea-8e74-48b6-930a-8fe59caab1a3)
https://projects.invisionapp.com/share/N3FL98EAWXY#/screens/276277803

**Comment by OhadRon** [comment]
Made a generic autocomplete that accepts a `searchFunction` prop with a signature `(inputString, callback)`
