### ISSUE TITLE
implement the ticket destinations picker component

### ISSUE THREAD

**Issue by barakd** [dorldor/help-on-the-way#58]
We need to implement a destinations picker component for the ticket flow.
We want to have a special picker, that allows to choose the destinations part of a ticket.
Important: Do not spend time on time & distances calculations (we can add those later)![image.png](https://images.zenhubusercontent.com/5a515ed2a016c5b034bc46c7/6ad4e350-9799-42c4-b166-09f1fbba7aad)

https://projects.invisionapp.com/share/N3FL98EAWXY#/screens/276277814

**Comment by OhadRon** [comment]
Unless I'm missing anything, this doesn't do anything on top of the address picker I built on https://github.com/dorldor/help-on-the-way/issues/54

For some tickets (home only) there will be just one field, and for some (escort somewhere) there will be two, as needed.

**Comment by barakd** [comment]
So basically this component is a composition of the address picker along with a new component that manages many address pickers and builds this destination component composing different addresses
