### ISSUE TITLE
implement the group message component

### ISSUE THREAD

**Issue by barakd** [dorldor/help-on-the-way#60]
It should get a ticket data, and construct and display, the message that would describe the ticket, and will be sent to the users.
It also allows a manula edit of the message.
![image.png](https://images.zenhubusercontent.com/5a515ed2a016c5b034bc46c7/97937b5b-0bf1-43ec-867a-9be84d75db14)
https://projects.invisionapp.com/share/N3FL98EAWXY#/screens/276277814

**Comment by OhadRon** [comment]
I made it in a way the message is compiled from the ticket data and can be freely modified. Once modified it can be reset to compile the default template. 
The component emits an initial compiled value and as the value changes.
