### ISSUE TITLE
tickets table component

### ISSUE THREAD

**Issue by barakd** [dorldor/help-on-the-way#65]
We need to create the tickets table component.
Given a tickets array, displays it, and allows to see specific ticket details.
![image.png](https://images.zenhubusercontent.com/5a515ed2a016c5b034bc46c7/72d1c7c4-bf0d-454b-97ea-e0718a6a5eec)
https://projects.invisionapp.com/share/N3FL98EAWXY#/screens/276277798

**Comment by IdoMor** [comment]
implemented under PR 26
