### ISSUE TITLE
elder creation functional

### ISSUE THREAD

**Issue by barakd** [dorldor/help-on-the-way#70]

**Comment by OhadRon** [comment]
I'll start by building a modal that can add an elder independently of the ticket creation flow, as illustrated in https://projects.invisionapp.com/share/N3FL98EAWXY#/screens/279666323

**Comment by barakd** [comment]
@OhadRon Sounds good, do note that I have already created a modal component for our use of these flows, see https://github.com/dorldor/help-on-the-way/blob/master/specialist-dashboard/src/components/layout/FloatingScreen.vue

**Comment by OhadRon** [comment]
@barakd Trying to figure out how the FloatingScreen works. Where is the state that says whether we should show it or not? I see a `showTickerModal` method in `SideBar.vue` but it's not called anywhere. I see the `FloatingScreen` component is a child of `NewTicketButton` with a slot of `TicketWizard`. 

Does the `target` attribute of the `FloatingScreen` (and hence the `b-popover`) determines which DOM id triggers the popover? 😯

**Comment by barakd** [comment]
@OhadRon see https://github.com/dorldor/help-on-the-way/blob/master/specialist-dashboard/src/components/features/ticket/create/NewTicketButton.vue

**Comment by barakd** [comment]
Done
