### ISSUE TITLE
Implement the new dashboard layout 

### ISSUE THREAD

**Issue by barakd** [dorldor/help-on-the-way#84]
We need to adjust the dashboard layout to match the new design.
![image.png](https://images.zenhubusercontent.com/5a515ed2a016c5b034bc46c7/15bfc452-1572-4249-8d0b-b29617c6ea74)

https://projects.invisionapp.com/share/N3FL98EAWXY#/screens/279666308

**Comment by barakd** [comment]
We need to adjust the dashboard layout to match the new design.
![image.png](https://images.zenhubusercontent.com/5a515ed2a016c5b034bc46c7/15bfc452-1572-4249-8d0b-b29617c6ea74)

https://projects.invisionapp.com/share/N3FL98EAWXY#/screens/279666308

**Comment by OhadRon** [comment]
Still needs icons & some CSS tweaks to make this more similar to the wireframe, but mostly done.

**Comment by barakd** [comment]
@OhadRon I know, this ticket is to finish those tweaks, about the icons, will add the font icon soon, so we can have them as well.
